### ISSUE TITLE
Add details to Participants.txt

### ISSUE THREAD

**Issue by ANIMO-07** [ANIMO-07/hacktoberfest2020#4]

**Comment by styles3544** [comment]
I'd like to contribute, what do i need to do? @ANIMO-07

**Comment by hanyangl** [comment]
Submitted my PR above https://github.com/ANIMO-07/hacktoberfest2020/pull/14, thanks!

**Comment by prabhu4444** [comment]
I'd like to contribute, what should I do?

**Comment by ananya8226** [comment]
I'd like to contribute, what shall i do?

**Comment by KailashMaden** [comment]
Why its going so delay? Since, i have already pushed for PR still no response in action. Feels so sad.
